# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-16 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': '文章'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
