# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180216_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='无标题', max_length=128, verbose_name='标题'),
        ),
    ]
