# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-17 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20180216_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
