# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_like',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
