# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-08 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
