# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_wall', '0002_confession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='motion',
            field=models.CharField(choices=[('To', 'To'), ('Found', 'Found')], max_length=5),
        ),
    ]
