# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-08 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_wall', '0003_auto_20180308_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='motion',
            field=models.CharField(choices=[('To', 'To'), ('Find', 'find')], max_length=5),
        ),
    ]
