# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-15 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession_wall', '0005_auto_20180314_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='location_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='location_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
