# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-15 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession_wall', '0007_auto_20180315_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='location_to',
        ),
    ]
